[phases.setup]
nixPkgs = ['python39', 'gcc', 'gfortran']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 app:app'
